name: Build

on:
  push:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build LaTeX resumes
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            resumes/en/resume.tex
            resumes/pt-br/curriculo.tex
      
      - name: Upload generated PDFs to GitHub Actions Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: resumes
          path: |
            *.pdf